configfile: 'config/config.yaml'

from pathlib import Path
import os

results = Path(config['output_directory'])
fastq_folder = Path(config['fastq_folder'])
final_merged_vcf = results / 'clair3_multisample' / 'merged_multisample.vcf.gz'

all_samples = [f.name.replace('.fastq.gz', '') for f in fastq_folder.glob('*.fastq.gz')]
sample_subset = config['sample_subset']

rule all:
	input:
		# rules.snpeff_all.input,
		# merged_vcf = final_merged_vcf,
		copied_snakefile = results / 'config' / 'Snakefile',
		copied_config = results / 'config' / 'config.yaml',
		copied_targets = results / 'config' / 'targets.tsv',
		clair3_vcf = expand(results / 'clair3_samples' / "{sample}" / 'merge_output.vcf.gz', sample = all_samples)

module snp_eff_annotation:
	snakefile:
		github(
			"simkin-bioinformatics/snp_eff_annotation", 
			path = "/workflow/Snakefile", 
			commit = "978e100c3434661dc47f2620cd591d581be70d43"
		)
	config: config

# use rule * from snp_eff_annotation exclude copy_config as snpeff_*

# use rule run_snp_eff from snp_eff_annotation as snpeff_run_snp_eff with:
# 	input:
# 		snp_eff_config = results / 'snpEff_processing' / 'snpEff.config',
# 		snp_eff_database = (
# 			results / 'snpEff_processing' / 'data' / config['genome_database_name'] / 'sequence.bin'
# 		),
# 		merged_vcf = final_merged_vcf

rule copy_files:
	input:
		original_snakefile = 'workflow/Snakefile',
		original_config = 'config/config.yaml',
		original_targets = config['targets_tsv'],
	output:
		copied_snakefile = results / 'config' / 'Snakefile',
		copied_config = results / 'config' / 'config.yaml',
		copied_targets = results / 'config' / 'targets.tsv',
	shell:
		'''
		cp {input.original_snakefile} {output.copied_snakefile}
		cp {input.original_config} {output.copied_config}
		cp {input.original_targets} {output.copied_targets}
		'''

rule run_minimap:
	input:
		genome = config['genome_fasta'],
		sample = fastq_folder / '{sample}.fastq.gz'
	output:
		aligned_sam = results / 'sam_files' / '{sample}_output.sam'
	shell:
		'minimap2 -ax map-ont -o {output.aligned_sam} {input.genome} {input.sample}'

rule index_genome:
	input:
		genome = config['genome_fasta']
	output:
		genome_index = config['genome_fasta'] + '.fai'
	shell:
		'samtools faidx {input.genome}'

rule index_and_sort_sam:
	input:
		aligned_sam = results / 'sam_files' / '{sample}_output.sam'
	output:
		sorted_bam = results / 'sorted_bam_files' / '{sample}_output_sorted.bam',
		indexed_bam = results / 'sorted_bam_files' / "{sample}_output_sorted.bam.csi",
	shell:
		'''
		samtools sort --write-index -o {output.sorted_bam} {input.aligned_sam}
		'''

rule run_clair3:
	input:
		genome = config['genome_fasta'],
		genome_index = config['genome_fasta']+'.fai',
		indexed_bam = results / 'sorted_bam_files' / "{sample}_output_sorted.bam.csi",
		sorted_bam = results / 'sorted_bam_files' / "{sample}_output_sorted.bam",
	params:
		model_path = config['model_path'],
		snp_min_af = config['snp_min_af'],
		indel_min_af = config['indel_min_af'],
	output:
		clair3_vcf = results / 'clair3_samples' / "{sample}" / 'merge_output.vcf.gz'
	shell:
		'''
		run_clair3.sh \
			--bam_fn={input.sorted_bam} \
			--ref_fn={input.genome} \
			--threads=6 \
			--platform=ont \
			--model_path={params.model_path} \
			--output=$(dirname {output.clair3_vcf}) \
			--print_ref_calls \
			--include_all_ctgs \
			--gvcf \
			--no_phasing_for_fa \
			--sample_name={wildcards.sample} \
			--snp_min_af={params.snp_min_af} \
			--indel_min_af={params.indel_min_af}
		'''

# rule index_vcf:
# 	input:
# 		clair3_vcf = results / 'clair3_samples' / '{sample}' / 'merge_output.vcf.gz'
# 	output:
# 		vcf_index = results / 'clair3_samples' / '{sample}' / 'merge_output.vcf.gz.csi'
# 	shell:
# 		'bcftools index {input.clair3_vcf}'

# rule merge_vcfs:
# 	input:
# 		clair3_vcfs = expand(
# 			results / 'clair3_samples' / '{sample}' / 'merge_output.vcf.gz', 
# 			sample=all_samples),
# 		vcf_indices = expand(
# 			results / 'clair3_samples' / '{sample}' / 'merge_output.vcf.gz.csi', 
# 			sample=all_samples)
# 	output:
# 		merged_vcf = final_merged_vcf
# 	shell:
# 		'''
# 		bcftools merge \
# 			{input.clair3_vcfs} \
# 			--force-samples \
# 			-O z \
# 			-o {output.merged_vcf}
# 		'''
