[workspace]
authors = ["Charlie Simkin <charlie.simkin@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "clair3-nanopore"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
clair3 = "pixi install -a && snakemake --unlock && snakemake -c 8 --rerun-incomplete"

[dependencies]
snakemake = ">=9.19.0,<10"
minimap2 = ">=2.30,<3"
samtools = ">=1.23.1,<2"
clair3 = ">=2.0.0,<3"
bcftools = ">=1.23.1,<2"
snpeff = ">=5.4.0c,<6"
