fastq_folder: 'resources/fastq'
genome_fasta: 'resources/PlasmoDB-62_Pfalciparum3D7_Genome.fasta'
genome_gff: 'resources/PlasmoDB-62_Pfalciparum3D7.gff'
output_folder: results
targets_tsv: 'config/targets.tsv'

#name and description of a snpEff database to be built
genome_database_name: 'plasmoDB_3D7_v62'
database_description: 'A database for plasmoDB version 62'

#filtering settings for clair3 - leave these alone for now
snp_min_af: 0.000
indel_min_af: 0.000
