fastq_folder: '/Users/charlie/data/MSMT_catherine_ONT_files/Lab_strains_ONT'
genome_fasta: '/Users/charlie/data/gatk4-illumina_test_data/PlasmoDB-62_Pfalciparum3D7_Genome.fasta'
genome_gff: '/Users/charlie/data/gatk4-illumina_test_data/PlasmoDB-62_Pfalciparum3D7.gff'
output_directory: 'results'
model_path: '/Users/charlie/data/clair3_models/r1041_e82_400bps_sup_v410'
targets_tsv: 'config/targets.tsv'

#name and description of a snpEff database to be built
genome_database_name: 'plasmoDB_3D7_v62'
database_description: 'A database for plasmoDB version 62'

#filtering settings for clair3 - leave these alone for now
snp_min_af: 0.000
indel_min_af: 0.000

sample_subset:
  - PM2
  - JS-2
  - JS-0-5-7